services:
  postgres:
    image: postgres:16-alpine
    container_name: the-patty-house-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thepattyhouse_orders
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - the-patty-house-network

volumes:
  postgres_data:

networks:
  the-patty-house-network:
    driver: bridge
